### ISSUE TITLE
О полезности просмотра другого варианта кода

### ISSUE THREAD

**Issue by ambernou** [dp140482/SimpleShopProject#6]
Если не против, то в ответ тоже напишу пару наблюдений:
1. Большой блок LUXIROUS & TRENDY / ACCESORIES на главной странице в текущем исполнении не на всю ширину и затемнение как для маленького блока, наверное издержки адаптива.
2. Иконки соц.сетей в футере не совсем по дизайну макета исполнены: при наведении фон меняется, а цвет символа остается чёрным, хотя должен быть белым.
3. Ещё у меня была проблема с карточкой товара, у вас эти блоки называются card-block. При добавлении ссылки на весь блок между картинкой и div'ом с описанием товара появился отступ в несколько пикселей. С его происхождением я так и не разобралась, как убрать - тоже. Взяла ваше скромное решение и сделала весь фон ссылки сереньким. Теперь хотя бы глаз не режет.

**Comment by dp140482** [comment]
Все недочёты и баги исправлены.
